
from PyQt5 import QtCore, QtGui, QtWidgets


class Add_New_Batch_Frame:
    def __init__(self,centralWidget):
        self.frame_addNewBatch = QtWidgets.QFrame(centralWidget)
        self.frame_addNewBatch.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_addNewBatch.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_addNewBatch.setObjectName("frame_addNewBatch")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_addNewBatch)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_batchName = QtWidgets.QLineEdit(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_batchName.setFont(font)
        self.lineEdit_batchName.setObjectName("lineEdit_batchName")
        self.verticalLayout_2.addWidget(self.lineEdit_batchName)
        self.label_3 = QtWidgets.QLabel(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_batchFees = QtWidgets.QLineEdit(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_batchFees.setFont(font)
        self.lineEdit_batchFees.setObjectName("lineEdit_batchFees")
        self.verticalLayout_2.addWidget(self.lineEdit_batchFees)
        self.label_4 = QtWidgets.QLabel(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.lineEdit_batchSheetUrl = QtWidgets.QLineEdit(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_batchSheetUrl.setFont(font)
        self.lineEdit_batchSheetUrl.setObjectName("lineEdit_batchSheetUrl")
        self.verticalLayout_2.addWidget(self.lineEdit_batchSheetUrl)
        self.label_5 = QtWidgets.QLabel(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.calendarWidget_batchStartDate = QtWidgets.QCalendarWidget(self.frame_addNewBatch)
        self.calendarWidget_batchStartDate.setObjectName("calendarWidget_batchStartDate")
        self.verticalLayout_2.addWidget(self.calendarWidget_batchStartDate)
        self.pushButton_createBatch = QtWidgets.QPushButton(self.frame_addNewBatch)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.pushButton_createBatch.setFont(font)
        self.pushButton_createBatch.setObjectName("pushButton_createBatch")
        self.verticalLayout_2.addWidget(self.pushButton_createBatch)

        self.label.setText("Add New Batch")
        self.label_2.setText("Batch Name")
        self.label_3.setText("Batch Fees")
        self.label_4.setText("Batch Sheet Url")
        self.label_5.setText("Select Starting Date")
        self.pushButton_createBatch.setText("Create Batch")


