# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Main_UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(659, 275)
        self.mainWin=MainWindow
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setObjectName("pushButton_back")
        
        self.label_msg = QtWidgets.QLabel(self.centralwidget)
        self.label_msg.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_msg.setFont(font)
        self.label_msg.setText("")
        self.label_msg.setTextFormat(QtCore.Qt.AutoText)
        self.label_msg.setObjectName("label_msg")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def resetLayout(self):
        self.verticalLayout_3.addWidget(self.pushButton_back, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.label_msg)
        self.mainWin.resize(659, 275)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tuffle Fees Management App"))
        
        self.pushButton_back.setText(_translate("MainWindow", "<-- Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Main_UI()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
