from PyQt5 import QtCore, QtGui, QtWidgets


class Menu_Frame:
    def __init__(self,centralWidget):
        self.frame_menu = QtWidgets.QFrame(centralWidget)
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_menu)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.frame_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton_addNewBatch = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_addNewBatch.setFont(font)
        self.pushButton_addNewBatch.setObjectName("pushButton_addNewBatch")
        self.verticalLayout.addWidget(self.pushButton_addNewBatch)
        self.pushButton_showBatchData = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_showBatchData.setFont(font)
        self.pushButton_showBatchData.setObjectName("pushButton_showBatchData")
        self.verticalLayout.addWidget(self.pushButton_showBatchData)
        self.pushButton_downloadBatchData = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_downloadBatchData.setFont(font)
        self.pushButton_downloadBatchData.setObjectName("pushButton_downloadBatchData")
        self.verticalLayout.addWidget(self.pushButton_downloadBatchData)
        self.pushButton_sendFeesReminder = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_sendFeesReminder.setFont(font)
        self.pushButton_sendFeesReminder.setObjectName("pushButton_sendFeesReminder")
        self.verticalLayout.addWidget(self.pushButton_sendFeesReminder)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame_menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_addStudentData = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_addStudentData.setFont(font)
        self.pushButton_addStudentData.setObjectName("pushButton_addStudentData")
        self.verticalLayout_2.addWidget(self.pushButton_addStudentData)
        self.pushButton_deleteStudentData = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_deleteStudentData.setFont(font)
        self.pushButton_deleteStudentData.setObjectName("pushButton_deleteStudentData")
        self.verticalLayout_2.addWidget(self.pushButton_deleteStudentData)
        self.pushButton_showStudentData = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_showStudentData.setFont(font)
        self.pushButton_showStudentData.setObjectName("pushButton_showStudentData")
        self.verticalLayout_2.addWidget(self.pushButton_showStudentData)
        self.pushButton_updateStudentData = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.pushButton_updateStudentData.setFont(font)
        self.pushButton_updateStudentData.setObjectName("pushButton_updateStudentData")
        self.verticalLayout_2.addWidget(self.pushButton_updateStudentData)
        self.horizontalLayout_2.addWidget(self.frame_2)

        self.label.setText("Batches")
        self.pushButton_addNewBatch.setText("Add New Batch")
        self.pushButton_showBatchData.setText("Show Batch Data")
        self.pushButton_downloadBatchData.setText("Download Batch Data")
        self.pushButton_sendFeesReminder.setText("Send Fees Reminder")
        self.label_2.setText("Students")
        self.pushButton_addStudentData.setText("Add Student Data")
        self.pushButton_deleteStudentData.setText("Delete Student Data")
        self.pushButton_showStudentData.setText("Show Student Data")
        self.pushButton_updateStudentData.setText("Update Student Data")